### ISSUE TITLE
Add custom headers to s3 api requests

### ISSUE THREAD

**Issue by patogordo** [becem-gharbi/nuxt-s3#10]
## Reason

I have a custom authentication/authorization middleware, and I want to protect the s3 routes with it.

**Comment by becem-gharbi** [comment]
There is `s3:auth` hook to pass custom headers. Did you have any issues using it?

https://nuxt-s3.bg.tn/usage/authorization#authorization

**Comment by patogordo** [comment]
Yes, I have created the Nuxt Plugin, but it does not send the Custom Header in the request.

## Plugin

<img width="389" alt="Captura de Tela 2024-02-27 às 14 15 43" src="https://github.com/becem-gharbi/nuxt-s3-edge/assets/59514690/65bc92cd-5e04-4aca-bc5d-345a61cb527d">

## Header Log in the Middleware

<img width="454" alt="Captura de Tela 2024-02-27 às 14 17 02" src="https://github.com/becem-gharbi/nuxt-s3-edge/assets/59514690/b085d330-0e1b-4cb3-aac3-d83ca2bd7bb2">
<br/><br/>
<img width="117" alt="Captura de Tela 2024-02-27 às 14 15 27" src="https://github.com/becem-gharbi/nuxt-s3-edge/assets/59514690/eadaf77c-7d1f-4c37-a9e4-1359789fc0a6">


Am I doing something wrong?

-----

I've seen that the meta object was sent correctly, and I could send the header in there, but I think it is a work around and also a security vulnerability, because it saves the header into the file metadata.

Example:

<img width="394" alt="Captura de Tela 2024-02-27 às 14 28 24" src="https://github.com/becem-gharbi/nuxt-s3-edge/assets/59514690/dc94daf5-0728-4725-843d-8d421528c879">

**Comment by becem-gharbi** [comment]
I'm not able to reproduce this issue. Can you make sure that the header is set on the request?

**Comment by patogordo** [comment]
After deleting the `.nuxt` folder and generating it again the plugin works, I think that nuxt have not identified that the s3 plugin was created, sorry for the inconvenient and thank you for the attention.
