### ISSUE TITLE
Can't install the old version

### ISSUE THREAD

**Issue by A1naz** [becem-gharbi/nuxt-s3#14]
Could you please make an older version of the library available(0.2.6)?
During the build the following error comes out

ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@bg-dev/nuxt-s3/-/nuxt-s3-0.2.6.tgz: Not Found - 404

No authorization header was set for the request.
{"code":1,"message":"The command '/bin/sh -c pnpm install' returned a non-zero code: 1"}
The command '/bin/sh -c pnpm install' returned a non-zero code: 1
Build has failed!

**Comment by becem-gharbi** [comment]
Hi, the older module is not stable and has been deprecated 8 months ago with a warning to migrate if needed to this one. I just republish it under `deprecated` tag [link](https://www.npmjs.com/package/@bg-dev/nuxt-s3/v/0.2.8).

```bash
npm i @bg-dev/nuxt-s3@deprecated
```

![image](https://github.com/becem-gharbi/nuxt-s3/assets/99251251/783eb3a8-383b-4795-ba43-48a64d45f9d7)

**Comment by A1naz** [comment]
> Hi, the older module is not stable and has been deprecated 8 months ago with a warning to migrate if needed to this one. I just

Thank you!)))<3
