### ISSUE TITLE
Error on upload using Vercel  "Not Implemented"

### ISSUE THREAD

**Issue by roberthgonz-ba** [becem-gharbi/nuxt-s3#8]
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Header>Transfer-Encoding</Header><RequestId>KTV1RB2K6FKVMNH4</RequestId><HostId>YKFRIkbpJxVX6xFNvpYKKBlITTUumTTPbmc49smzwLSkMTqmHKGAmQEb1r3XcQ8joqleAXhfRQM=</HostId></Error>

**Comment by becem-gharbi** [comment]
Hi, to understand the issue please provide a reproduction or a detailed description.

**Comment by roberthgonz-ba** [comment]
Hi @becem-gharbi. Here is an example:


Request code:
```js
const url = await upload(fileLogo.value, {
  url: form.value.logo,
  prefix: 'logos/',
})
```

Response:
![image](https://github.com/becem-gharbi/nuxt-s3-edge/assets/128686571/8443f376-1e17-458e-a7a7-cbd35a164730)

![image](https://github.com/becem-gharbi/nuxt-s3-edge/assets/128686571/ceca140e-596a-4dd1-83f6-9bc01c6b750b)

**Comment by becem-gharbi** [comment]
~Just to check, in module configuration have you set `driver` to `s3`?~

**Edit** 
The error is not related to the module nor to the hosting platform but rather to the S3 provider which seems to reject the PutObject operation. I will check this later. Thanks for reporting this issue, appreciate it.

**Comment by roberthgonz-ba** [comment]
> ~Just to check, in module configuration have you set `driver` to `s3`?~
> 
> **Edit** The error is not related to the module nor to the hosting platform but rather to the S3 provider which seems to reject the PutObject operation. I will check this later. Thanks for reporting this issue, appreciate it.

Thank you for your reply!

**Comment by becem-gharbi** [comment]
This is potentially related to missing `content-type` header. You can try the edge release [v1.1.4-edge](https://www.npmjs.com/package/nuxt-s3/v/1.1.4-edge). Please let me know if it solves the issue.

**Comment by roberthgonz-ba** [comment]
Hi @becem-gharbi

I tried it with the new version... I got this

<no response>

[nuxt] [request error] [unhandled] [500] [PUT] "https://s3.eu-south-2.amazonaws.com/bernersads-web-assets/logos/5a5cf707-684b-444c-b16e-c8ce08b40fe7.png": <no response> fetch failed
  at async $fetchRaw2 (./chunks/nitro/vercel.mjs:2931:14)  
  at async $fetch2 (./chunks/nitro/vercel.mjs:2964:15)  
  at async Object.setItemRaw (./chunks/nitro/vercel.mjs:4561:9)  
  at async ./chunks/nitro/vercel.mjs:8701:5  
  at async Object.handler (./chunks/nitro/vercel.mjs:2495:19)  
  at async toNodeHandle (./chunks/nitro/vercel.mjs:2684:7)  
  at async Server.<anonymous> (./___vc/__launcher/bridge-server-72TT5FOD.js:1:8478)

**Comment by becem-gharbi** [comment]
Hi @roberthgonz-ba, I'm able to reproduce this one. The error is related to a mismatch of the content length on Vercel. I have pushed a patch [v1.1.10-edge](https://www.npmjs.com/package/nuxt-s3/v/1.1.10-edge). Please let me know if it solves the issue. Thanks for your time.

**Comment by roberthgonz-ba** [comment]
@becem-gharbi Now it works correctly. Thank you very much for your work!
